# Generated by Django 5.2.4 on 2025-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='complaint_image/'),
        ),
    ]
