# Generated by Django 5.2.4 on 2025-08-12 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_alter_complain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 9, 8, 41, 548159, tzinfo=datetime.timezone.utc)),
        ),
    ]
