# Generated by Django 5.2.4 on 2025-08-12 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0004_alter_complain_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='complaint',
        ),
        migrations.AddField(
            model_name='complain',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='complaints', to='village.tag'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 11, 49, 12, 10374, tzinfo=datetime.timezone.utc)),
        ),
    ]
