# Generated by Django 5.2.4 on 2025-08-13 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0005_remove_tag_complaint_complain_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='area_sq_km',
            field=models.FloatField(blank=True, help_text='Village area in square kilometers', null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='head_of_village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='village_images/'),
        ),
        migrations.AddField(
            model_name='village',
            name='literacy_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of literate people in the village', max_digits=5),
        ),
        migrations.AddField(
            model_name='village',
            name='number_of_health_centers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='number_of_houses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='number_of_schools',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='post_code',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='village',
            name='total_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 6, 52, 29, 541973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='village',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
