# Generated by Django 5.2.4 on 2025-08-13 13:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0006_village_area_sq_km_village_established_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='image',
        ),
        migrations.AlterField(
            model_name='complain',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 13, 12, 44, 609275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='VillageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='village_images/')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='village.village')),
            ],
        ),
    ]
