# Generated by Django 5.2.4 on 2025-08-13 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0007_remove_village_image_alter_complain_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='village_images/'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 14, 10, 12, 112013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='VillageImage',
        ),
    ]
