# Generated by Django 5.2.4 on 2025-08-14 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0008_village_image_alter_complain_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 14, 50, 23, 21475, tzinfo=datetime.timezone.utc)),
        ),
    ]
