# Generated by Django 5.2.4 on 2025-08-15 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0009_alter_complain_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 4, 39, 17, 564536, tzinfo=datetime.timezone.utc)),
        ),
    ]
