# Generated by Django 5.2.4 on 2025-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0012_alter_complain_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile_picture'),
        ),
        migrations.AlterField(
            model_name='village',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
